### ISSUE TITLE
Rigging functions in a package namespace

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#10]
must be done in `.onLoad()` .

Consider a package (such as dm) that imports `dplyr::filter()` . When using `boomer::rigger()` to rig a function that uses `filter()` (such as `dm_insert_zoomed_outgoing_fks()` in cynkra/dm@ee564d1a430327d412663892e7dfbbea8de0fffd), that function environment's `filter` shim points to `stats::filter()` .

The problem is circumvented by adding the following to `.onLoad()` :

```r
  dm_insert_zoomed_outgoing_fks <<- boomer::rig(dm_insert_zoomed_outgoing_fks)
```

I'm sorry, it seems this makes `rigger()` less useful than anticipated.

**Comment by krlmlr** [comment]
If we can't fix that, a rigging API similar to `trace()` would be helpful to avoid repetition.

**Comment by moodymudskipper** [comment]
Good catch! in `boom()` the functions have to be evaluated in the caller environment, but in `rig` they should be evaluated in the function environment, as they are now.

I reproduced and solved the issue with the following package code : 

```
#' @importFrom dplyr filter
NULL

test <- boomer::rigger() + function() {
  filter(cars, speed == 4)
}
```

Please tell me if it works on your side.

0e302e941f5c963a53ce8133eb123597f07eaa17

**Comment by krlmlr** [comment]
We need to add the `ignore` argument to `rigger` :upside_down_face:

**Comment by moodymudskipper** [comment]
yes I saw that a few minutes ago :), done here b228fa11e630b2626d33df18c1c8b8288f14e7c6

**Comment by moodymudskipper** [comment]
I think this can be closed
