### ISSUE TITLE
Alternative wrapping strategy

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#11]
Have you considered explicitly wrapping, instead of shimming functions? Are there downsides? I think this would also solve #10.

`boom(1 + 2 * 3)` could create `boomer:::wrapx(1 + boomer:::wrapx(2 * 3))`, with `wrapx()` along the lines of:

```r
wrapx <- function(code) {
  source <- deparse1(unwrapx(substitute(code))) # or we could use the original srcref?

  out <- force(code)
  # side effects
  out
}

unwrapx <- function(expr) {
  # Walk AST to remove boomer:::wrapx() calls for pretty printing
}
```

The advantage is that we could also boom all inputs. This isn't too important for constants but perhaps much more for variables:

```r
boomer:::wrapx(boomer:::wrapx(1) + boomer:::wrapx(boomer:::wrapx(2) * boomer:::wrapx(3)))
```

It *might* simplify the internal code too.

**Comment by krlmlr** [comment]
Another advantage: if a rigged function calls another rigged function, currently the inner function doesn't seem to show the output. I suspect the alternative implementation would support that.

**Comment by moodymudskipper** [comment]
This works for me : 

``` r
library(boomer)
fun1 <- rigger() + function(x) {
  x + fun2(2)
}

fun2 <- rigger() + function(y) {
  y + 3
}

fun1(10)
#> y + 3
#> [1] 5
#> x + fun2(2)
#> [1] 15
#> [1] 15
```

<sup>Created on 2021-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by moodymudskipper** [comment]
I don't fully understand your suggestion, but wouldn't there be issues with NSE ?

**Comment by krlmlr** [comment]
I think it would work just fine with tidy evaluation. Of course we can't rely on this.
