### ISSUE TITLE
Modularize code

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/boomer#15]
Copy/pastes were fine when code was simpler to avoid adding abstraction layers, but now it's starting to be hard to maintain.

**Comment by krlmlr** [comment]
But then I haven't entirely thought it through.

**Comment by moodymudskipper** [comment]
much better now

e7703ebe746b431a18c02e31a4697a883f7ae7f1

**Comment by moodymudskipper** [comment]
Time for round 2.

`wrap_unclocked` and `wrap_clocked` should be merged, too much copy and paste.

With `bquote`, use idiom `bquote(.(if (cond) quote(this) else quote(that)))` rather than `bquote(if (.(cond)) this else that)`. It looks more complicated but will build cleaner functions.

Maybe merge `double_colon()` and `tripl_colon()` too.

**Comment by moodymudskipper** [comment]
much better now

2f88bfa73e227e0260d7614dd6f057a719d1e2a1

4ead247d15759ffb421289a3392b1fd2e2786929

236e60e2e8aee41756fd9e6dad108933ac7255a2
