### ISSUE TITLE
Cant install it on windows 10 x64

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [moodymudskipper/boomer#24]
remotes::install_github("moodymudskipper/boomer") does not work on windows, R 4.0.4.

I get: Error: Failed to install 'unknown package' from GitHub:
  cannot open the connection.
Backtrace:
 1. remotes::install_github("moodymudskipper/boomer")
 2. remotes:::install_remotes(...)
 3. base::tryCatch(...)
 4. base:::tryCatchList(expr, classes, parentenv, handlers)
 5. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6. value[[3L]](cond)

**Comment by moodymudskipper** [comment]
Unfortunately I can't reproduce this on my very similar system (windows 10 x64 R 4.0.2), copy pasting your installation instruction above.
Can you install other github packages without problems ?

**Comment by moodymudskipper** [comment]
@Andrzej-Andrzej I'll be happy to reopen if the issue persists
