### ISSUE TITLE
Not working with %>%

### ISSUE THREAD

**Issue by amrrs** [moodymudskipper/boomer#3]
Hey @moodymudskipper Thanks for your work. `boom` doesn't seem to work with `%>%` for me. 

![image](https://user-images.githubusercontent.com/5347322/112537560-d8835180-8dd4-11eb-800b-bd953a086fff.png)

```
library(boomer)
library(magrittr)

mtcars %>%
  head(2) %>%
  subset(qsec > 17) %>%
  boom() 

```

Session Details:

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
[1] magrittr_1.5     
[2] boomer_0.0.0.9000

loaded via a namespace (and not attached):
 [1] ps_1.3.2         
 [2] digest_0.6.25    
 [3] R6_2.4.1         
 [4] reprex_0.3.0     
 [5] evaluate_0.14    
 [6] rlang_0.4.10     
 [7] rstudioapi_0.11  
 [8] fs_1.4.1         
 [9] callr_3.4.3      
[10] whisker_0.4      
[11] rmarkdown_2.6    
[12] tools_4.0.0      
[13] xfun_0.20        
[14] compiler_4.0.0   
[15] processx_3.4.2   
[16] clipr_0.7.0      
[17] htmltools_0.5.1.1
[18] knitr_1.28````

**Comment by moodymudskipper** [comment]
Hi and thanks for reporting! 

I cannot reproduce this issue unfortunately. I believe the most probable explanation is that the trick I use ony work with more recent versions of *{magrittr}*. Can you try to update *{magrittr}* ?

I believe if before reinstalling you do : 

```
debugonce(boom)
mtcars %>%
  head(2) %>%
  subset(qsec > 17) %>%
  boom() 
```

and go through the following step at the start of the function : 

```
  scs <- sys.calls()
  l <- length(scs)
  call_is_piped <-
    identical(scs[[l]][[2]], quote(.)) &&
    identical(scs[[l-1]][[1]], quote(`%>%`))
  if(call_is_piped) {
    call <- do.call(substitute, list(scs[[l]], list(. = scs[[l-1]][[2]])))
    eval.parent(call)
  }
```

you will find that `call_is_piped` will be `FALSE` and the `if` block won't be run.

This feature (piping to `boom()`) is a bit of a hack, but it's handy so I kept it, let me know if it works to update magrittr, if this is the issue I might try a more general approach that works for older versions.

**Comment by amrrs** [comment]
You are right the `call_is_piped` is `FALSE` 
![image](https://user-images.githubusercontent.com/5347322/112669145-5dc63f00-8e85-11eb-9d0b-8a00cac61940.png)

**Comment by amrrs** [comment]
And you are absolutely right again, updating `magrittr` made it work fine! 

```
[1] magrittr_2.0.1   
[2] boomer_0.0.0.9000
```

**Comment by moodymudskipper** [comment]
Awesome, I'm glad it worked!
