### ISSUE TITLE
Explicit symbols raise an error

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#30]
``` r
fun <- function(x) {
  xx <- rlang::ensym(x)
  xx
}

fun(xx)
#> xx

boomer::rig(fun)(xx)
#> rlang::ensym(x)
#> xx
#> Error in eval(expr, p): object 'xx' not found
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Are we unquoting implicitly somewhere? How to work around/fix?

**Comment by moodymudskipper** [comment]
This would work with : 

```
fun <- function(x) {
  rlang::ensym(x)
}
```

We probably need some `eval_bare` magic in `build_shimmed_assign`

**Comment by moodymudskipper** [comment]
It was an issue with substitute, a special case was made for language objects 789cfcd93741d962d37b04cc92b7c809def1c2ba
