### ISSUE TITLE
Nested calls and recursive rigged function calls, readable output ?

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/boomer#33]
There are a few ways to show that something changed (e.g. when we are exploding the calls of a rigged function called by another rigged function) : 

* indent
* change colors
* announce explicitly once
* remind at every step

Right now I tend to think that nested calls should be indented, and that a prefix `"my_rigged_function_name>"` before printing any call would make it easy to follow along when using `rig_in_namespace` on several functions that call each other.

I think announcing explicitly just once `"booming my_rigged_function_name"` is not possible without altering the function's body, which I feel might come back to bite us in some hard to debug corner cases, and bugs in debugging tools are not good for sanity.

**Comment by moodymudskipper** [comment]
Thanks to 498f9fb29cada971f628a497b6db5a9c8a98a326 and 962c54ef070f9d260fdf6864eaf35a84c18ec139

If we take the following:

``` r
foo <- function(x) {
  z <- subset(head(mtcars, 2), qsec > bar(x))
  rbind(z, z)
}

bar <- function(x) 2 * x - 1

foo(8)
#>                mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4       21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag   21   6  160 110  3.9 2.875 17.02  0  1    4    4
#> Mazda RX41      21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag1  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

rigging in namespace does : 

```
rig_in_namespace(foo, bar)
foo(8)
foo> · head(mtcars, 2)
              mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
bar> · · · · 2 * x
[1] 16
bar> · · · 2 * x - 1
[1] 15
bar> · · bar(x)
[1] 15
foo> · qsec > bar(x)
[1] TRUE TRUE
foo> subset(head(mtcars, 2), qsec > bar(x))
              mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
foo> rbind(z, z)
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4       21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag   21   6  160 110  3.9 2.875 17.02  0  1    4    4
Mazda RX41      21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag1  21   6  160 110  3.9 2.875 17.02  0  1    4    4
               mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4       21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag   21   6  160 110  3.9 2.875 17.02  0  1    4    4
Mazda RX41      21   6  160 110  3.9 2.620 16.46  0  1    4    4
Mazda RX4 Wag1  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

The indentation is not reset when entering a new function, it's global, it was easier this way, I don't know if it's good or bad.

**Comment by moodymudskipper** [comment]
We might make these optional but otoh we don't need 1000 parameters and I feel it's good this way. This kind of indentation might go too far if we implement a fully recursive boom though (https://github.com/moodymudskipper/boomer/issues/29 ), or maybe it won't in practical cases.

The current would look nice if we had two different colors and such as `foo> · head(mtcars, 2)` would be cyan as it is now and  `bar> · · · · 2 * x`  would be in another color, except for the 2 first dots that would stay cyan. It would make it very visual how we move in the call stack.

**Comment by moodymudskipper** [comment]
@krlmlr curious about your feelings on this

**Comment by krlmlr** [comment]
I think there might be a way to output only the first instance of each function, without altering the code. The first time we print, we set a flag, and reset it with `withr::defer()` as soon as the scope of the function ends. Too complicated?

Do we need to account for function names of different length? Does it affect the indent? Maybe add a newline after `>` ?

**Comment by moodymudskipper** [comment]
That's a good idea, not easy because their should be a different flag for each call of rigged function.

For function names length we can align them, since they're all fed to `rig_in_namespace` it's easy to pad the shorted ones with spaces to make the suffix the same length.

**Comment by moodymudskipper** [comment]
> a way to output only the first instance of each function

The idea above is complicated, but might be made simpler

* For most functions, the first called function is `{`
* `{` can be shimmed to fire `"<rigged_fun>"`  when entering, and `"</rigged_fun>"` when exiting, only the first time it's called
* It would switch a flag and switch it back on.exit, so nested calls would ignore it
* when `{` is not the first call, we can wrap the body around it, and `rig_in_namespace()` would warn that the body was slightly altered. 

The warning would be rare because this style is rare and we're less likely to `rig_in_namespace()` short functions, and the impactful consequences even rarer (metaprogramming functions, tracing at specific location...)

The flag needs to be associated with the environment, the easiest is to just have a `..FIRST_CURLY..` variable in the environment, `TRUE` by default.

**Comment by moodymudskipper** [comment]
meanwhile I think this is already better 49ac0be39f455e1dda5c93a0f042e3e16f039d85

![boomer1](https://user-images.githubusercontent.com/18351714/121380305-0c3a3600-c945-11eb-9d78-5f1aa140e0b3.Png)
![boomer2](https://user-images.githubusercontent.com/18351714/121380307-0cd2cc80-c945-11eb-999d-5c4a5e0e96df.Png)

**Comment by moodymudskipper** [comment]
In the end I could make it work with `withr::defer_parent`, I reworked everything to make the display more intuitive and hopefully satisfy https://github.com/moodymudskipper/boomer/issues/34 .

Emoticons don't look nice in R Gui : 

![image](https://user-images.githubusercontent.com/18351714/121431827-335f2a80-c97a-11eb-9411-db7802a9d341.png)

On reprexes and markdown docs including README it looks terrible, maybe we can fix it by providing alternatives when `interractive()` is `FALSE`.

**Comment by krlmlr** [comment]
Thanks, I'll give it a shot. Would that extra newline look too terrible in the first example?

**Comment by moodymudskipper** [comment]
I'm hesitant to display the full call when igniting the bomb, it would be more verbose/redundant, but when calls are not multiline the redundancy is not that bad.

Maybe it could print the first line of the call followed by `...`, so single line calls would be displayed entirely and things like the above would be easier to read : 

 
![image](https://user-images.githubusercontent.com/18351714/122112227-e15a5100-ce20-11eb-8a0b-99f29817e1c8.png)


And `if` calls for instance would most of the time display `if (cond) { ...`

**Comment by moodymudskipper** [comment]
Done with 1bc9f13a4a6c7c5e6151a51fc14d1002d1bd1211

I also took the opportunity to collapse a call when the arguments are symbols or numbers ("atomic" in the boomer sense)

    boomer::boom(3/4 * !(x==1) + 1/4 * (x==1))

![image](https://user-images.githubusercontent.com/18351714/122782372-f4ea3980-d2b0-11eb-8534-67dc99d53e0b.png)

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa <- bbbbbbbbbbbbbbbbbbb <- identity
boom(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(bbbbbbbbbbbbbbbbbbb(1)))
```

![image](https://user-images.githubusercontent.com/18351714/122783872-3deebd80-d2b2-11eb-9baf-9c98d8156879.png)

```
boom({
  iris %>% head() %>% subset(Petal.Length > 1.4)
})
```

![image](https://user-images.githubusercontent.com/18351714/122788574-c1121280-d2b6-11eb-8f19-e795f9474e31.png)

Collapsing the calls is not 100% robust, one case where it breaks is in magrittr pipelines, due to how dot substitution works a call like `head(.)` might not contain atomic arguments. The workaround to make it work is to make the `.` symbol an exception, not super pretty but I think it's worth it since the potential "bug" is just an extra printed line in pipes (as `head(.)` aboveor `toupper(.)` below), or a missing line in corner cases that i couldn't produce with `substitute()` or `{{ }}`. 

![image](https://user-images.githubusercontent.com/18351714/122790926-10594280-d2b9-11eb-8043-6257cee197e3.png)

**Comment by moodymudskipper** [comment]
The 1st example of the issue, updated: 

![image](https://user-images.githubusercontent.com/18351714/122795467-a5f6d100-d2bd-11eb-8207-47739674ee03.png)
