### ISSUE TITLE
cli::symbol$ellipsis gives error

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#36]
``` r
cli::symbol$ellipsis
#> [1] "…"
boomer::boom(cli::symbol$ellipsis)
#> cli::symbol$ellipsis
#> Error: simpleError/error/condition
#> Error in .Primitive("$")(cli::symbol, ellipsis): object of type 'closure' is not subsettable
```

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by moodymudskipper** [comment]
Thanks, `double_colon` and `triple_colon` didn't support non function objects, fixed in 4bfc8f8ef024db05aaa00d1552559ce7cbd2426e
