### ISSUE TITLE
knitted output looks bad on windows with new output style

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/boomer#37]
A fix would be to use standard symbols when `interactive()` is `TRUE`, we could enter and exit a rigged function with ">>" and "<<", and arm and detonate the bomb with "O" and "X"

Might be relevant : https://stackoverflow.com/questions/44153072/unicode-with-knitr-and-rmarkdown

**Comment by moodymudskipper** [comment]
The README can be saved if we knit it through github actions, tough in any case it will look better with screen captures.

**Comment by krlmlr** [comment]
It looks good on UTF-8 enabled systems.

**Comment by moodymudskipper** [comment]
#43 seems to be the best we can do for now. `boom.safe_print` is set to `TRUE` before tests so they're consistent across systems (9c7e7714dfc0c0e501c79ee1383e9a8e552df80d).
