### ISSUE TITLE
Add to addinslist

### ISSUE THREAD

**Issue by daattali** [moodymudskipper/boomer#4]
Found out about this package today, very cool concept. I saw in the readme that it includes an addin, so you might want to add it to https://github.com/daattali/addinslist . Feel free to close the issue if not!

**Comment by moodymudskipper** [comment]
Thanks Dean, this is a good idea!

**Comment by moodymudskipper** [comment]
Hopefully will be solved by https://github.com/daattali/addinslist/pull/125 , closing already.
