### ISSUE TITLE
Print file + line information

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#41]
Looks like we can get the srcref from `sys.call()` ?

``` r
a <- function() {
  # dummy comment
  b() # located on the third line of the source file
}

b <- function() {
  call <- sys.call()
  file <- getSrcFilename(call)
  line <- unclass(getSrcref(call))[[1]]
  paste0(file, ":", line)
}

a()
#> [1] "<text>:3"
```

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

 The correct file name is returned when I run locally from a proper file.

**Comment by krlmlr** [comment]
A first test didn't show the correct information when run in production. Need to understand where the srcrefs are lost and if we can keep them.

**Comment by moodymudskipper** [comment]
Closed as "too hard and weird", see comments in linked PR
