### ISSUE TITLE
Can't boom() a function in .GlobalEnv

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#5]
``` r
fun <- function(x) {
  x
}

boomer::boom(fun(1:3))
#> Error in asNamespace(ns): not a namespace
```

<sup>Created on 2021-04-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by moodymudskipper** [comment]
Thanks!

Solved with https://github.com/moodymudskipper/boomer/commit/0ef6c569cd052bc1b69655d719c48d6bd7e445ca

``` r
fun <- function(x) {
  x
}

boomer::boom(fun(1:3))
#> 1:3
#> [1] 1 2 3
#> fun(1:3)
#> [1] 1 2 3
```

<sup>Created on 2021-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
