### ISSUE TITLE
Easier rigging

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#8]
Long form:

```r
fun <- function(x) {
  ...
}

# Repetition
fun <- boom::rig(fun)
```

Wrapping:

```r
# Closing parenthesis is far away
fun <- boom::rig(function(x) {
  ...
})
```

Reverse pipe:

```r
# Needs %<% in global namespace
fun <- boom::rig() %<% function(x) {
  ...
}
```

Maybe:

```r
fun <- function(x) {
  ...
}

# with a suitable implementation
boom::xxx(fun)
```

Or:

```r
# with a suitable implementation
fun <- boom::rigger + function(x) {
  ...
}
```

**Comment by moodymudskipper** [comment]
Thanks. 

When I designed `rig` I thought of having it have a side effect like `debug`, and we would have had `unrig` too.

I decided that wrapping into `rig()` for all uses was easier but it was almost a coin toss. 

It seems to me your use case is to create a function solely for the purpose of rigging it and debugging, it is a use case I had not considered. 

I'm open to implement a function or an argument to rig in place and à function to unrig, but I m not sure about how to name it. 

I think I like the rigger object.

**Comment by moodymudskipper** [comment]
@krlmlr I've implemented your `rigger` idea, with a twist, `rigger` is a function so we can still use `clock` and `print` parameters, let me know what you think! 

``` r
fun1 <- boomer::rigger() + function(x) x + 1 + 2
fun1(1)
#> x + 1
#> [1] 2
#> x + 1 + 2
#> [1] 4
#> [1] 4
fun2 <- boomer::rigger(TRUE, typeof) + function(x) x + 1 + 2
fun2(1)
#> x + 1
#> time: 0 us
#> [1] "double"
#> x + 1 + 2
#> time: 0.023 s
#> [1] "double"
#> [1] 4
```

<sup>Created on 2021-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Works for me, thanks!
