### ISSUE TITLE
pkgdown hex icon missing

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#9]
https://moodymudskipper.github.io/boomer/

![Screenshot from 2021-04-15 06-52-14](https://user-images.githubusercontent.com/1741643/114815755-23cac780-9db7-11eb-9fd5-da648fa9cd75.png)

**Comment by moodymudskipper** [comment]
The link pointed to "logo.PNG" and the logo file was named "logo.png".

It seems both github and pkgdown don't notice when a file is renamed by changing case only, making the fix more convoluted than it could be. Anyway, fixed!
